### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by shiva4983** [NHP95/ReportPortal-Katalon-Integration#3]
Hi @NHP95 ,

I am able successfully connect to the reportportal. Thank you.

is it possible to send the screenshot as well? Please help

Thanks

**Comment by NHP95** [comment]
You can attach screenshots by directly calling `captureScreenShotForReportportal` keyword inside your test cases.

**Comment by shiva4983** [comment]
yeah @NHP95 , I am about to update that i figured it out.

Thanks,

Siva
