### ISSUE TITLE
Send custom log message to mark a step pass or failed

### ISSUE THREAD

**Issue by shiva4983** [NHP95/ReportPortal-Katalon-Integration#4]
Hi @NHP95 ,

How to send a custom step and mark it with pass or failed?

Thanks,
Siva

**Comment by NHP95** [comment]
Hi @shiva4983,

Can you describe it more specifically? I'm afraid that the STEP you've mentioned is different from the one that I knew.

**Comment by shiva4983** [comment]
Hi @NHP95 ,

Thanks for the quick reply @NHP95 

I meant to ask KeywordUtil.markPassed and markFailed, but nevermind I figure it out. 

Also I would like to know can we attach file like csv or log files to the step?

Thanks,
Siva

**Comment by NHP95** [comment]
Yes @shiva4983,

I didn't implement such general functions, but it should be similar to attaching images since they're all attachments. For more details on this matter, you can refer to the `logScreenShot` method in the `LoggingService` class as a sample.

**Comment by shiva4983** [comment]
Sure @NHP95 Thanks a lot.
