### ISSUE TITLE
Screenshot every step in katalon by override keyword katalon

### ISSUE THREAD

**Issue by Fhadel** [NHP95/ReportPortal-Katalon-Integration#5]
Hi @NHP95 ,

I read the documentation and get some information about attach screenshot into report portal,
Do you think its possible to put the function **captureScreenShotForReportportal()** in only one place let say Listener 

My idea is first you define what step need to be screenshot is by create an array list to define which step will be screenshoot like this 

```
private static List<String> influencedKeywords = [
		'verifyElementPresent',
		'verifyEqual',
		'verifyElementVisible',
		'verifyElementText',
		'click',
		'setText',
		'setEncryptedText',
		'selectOptionByValue',
		'selectOptionByIndex',
		'sendRequest'
	]
```

Then, i got some function in katalon forum this function will highlight the element by refer to your test object ( https://forum.katalon.com/t/how-to-highlight-test-object-in-each-and-every-step/17408/46 ) 

And im stuck like how to combine your function **captureScreenShotForReportportal()** to this function 

```
public static void enlightWebUiBuiltInKeywords(List<String> additionalKeywords) {
		influencedKeywordsWeb.add(additionalKeywords)
		WebUI.metaClass.'static'.invokeMethod = { String keywordName, Object args ->
			if (isHighlightingCapable(influencedKeywordsWeb, keywordName, args)) {
				TestObject to = (TestObject)args[0]
				HighlightElement.on(to)
				screenshotAftermethodWeb(keywordName,to)
			}
			MetaMethod metaMethod = delegate.metaClass.getMetaMethod(keywordName, args)
			if (metaMethod != null) {
				return metaMethod.invoke(delegate, args)
			} else {
				throw new IllegalArgumentException("failed to find delegate.metaCLass.metaMethod(${keywordName},${args}).")
			}
		}
	}
```

i think this dashboard will be great to have these kind of function so you dont have to call the function **captureScreenShotForReportportal()** in each test cases you just control it from listener or custom keywords or else

how do you think? is it possible?

Thanks,
Fhadel

**Comment by NHP95** [comment]
Hi Fhadel,
Yes, I confirmed it's totally possible. Actually, I already had an implementation (not yet published) that could capture a screenshot on failure without explicitly call the capture function in the test case. All I did was to manipulate the hook provided in ReportPortalListener class.

You could achieve the same thing by utilizing the listener provided in ReportPortalListener class and BaseListener class.

**Comment by Fhadel** [comment]
Hi,

Thanks for reply me with that speed, so you say i need to look into ReportPortalListener and do tweak about the code of my Highlight in there? and what connected between ReportPortalListener with BaseListener?

Regards
Fhadel

**Comment by NHP95** [comment]
Yes, that's exactly what you need to do. **ReportPortalListener** contains implementation detail of the hooks provided in **BaseListener**. Specifically, you will need to provide your highlight implementation inside _beforeStepHandler_ and _afterStepHandler_
```java
               switch (event) {
			case ExecutionListenerEvent.AFTER_TEST_SUITE:
				afterSuiteHandler()
				break
			case ExecutionListenerEvent.BEFORE_TEST_CASE:
				beforeTestHandler(testParam[0])
				break
			case ExecutionListenerEvent.AFTER_TEST_CASE:
				afterTestHandler(testParam[0])
				break
			case ExecutionListenerEvent.BEFORE_TEST_STEP: // Run before each step
				beforeStepHandler(testParam)
				break
			case ExecutionListenerEvent.AFTER_TEST_STEP: // Run after each step
				afterStepHandler()
				break
			default:
				break
		}
```

**Comment by Fhadel** [comment]
Thanks man that give me a clearer path where to start the tweak 

but i still confuse in this method `logScreenShot()`, its used to send the screeshots into the HTML ReportPortal is it right? so the flow is method `captureScreenShotForReportportal()` send the screenshots file that capture into `logScreenShot()` function to be send by backend service 

am i correct? so basically i just need to call my HiglightElement method in `BaseListener`

**Comment by NHP95** [comment]
You're totally correct. And yes, you will need to put your HighLight implementation in the `BaseListener` class.

**Comment by Fhadel** [comment]
for the highlight its a success but for the screenshot that uploaded to ReportPortal im stuck, screenshot is taken but not sent into ReportPortal Server

here is snippet to the code afterSteop()

```
@Override
	public afterStepHandler(){
		println('cc')
		this.context.setState(ReportPortalState.STEP)
		if (!this.context.currentStep.isEmpty()) {
			this.createErrorSteps(this.context.getItem())
			this.createLogSteps(this.context.getItem())
			def ss = new ReportPortalContext()
			ss.captureScreenShotForReportportal()
		}
	}
```

**Comment by NHP95** [comment]
Putting in `captureScreenShotForReportportal` directly in the BaseListener doesn't produce any images. The `captureScreenShotForReportportal` will capture a screenshot then add to a list, and whenever you call the `logScreenshot`, it will scan the list to see if any screenshots available. If there is, it will send the captured screenshot to ReportPortal. You should modify this function as well because it was specified for the regular use as in the current version.
```java
private createLogSteps(stepId) {
		this.context.logSteps.each {
			if (this.isScreenShotStep(it['name'])) {
				def time = DateUtils.getISOCurrentDate('UTC')
				def name = it['name']
				screenShotClosure = {
					this.logging.logScreenShot(stepId, name, time)
				}
			}
			else {
				this.createDecriptionSteps(stepId,it['description'])
				this.logging.logInfo(stepId, it['name'])
			}
		}
		this.context.logSteps.clear()
	}
```

**Comment by NHP95** [comment]
Below is the code snippet that I used to log screenshot inside the listener:

```java
private createErrorSteps(stepId) {
		this.context.errors.each {
			if (!it['screenshot'].isEmpty()) {
				int numberOfScreenshots = it['screenshot'].size()
				for (int i = 0; i < numberOfScreenshots; i++) {
					this.logging.logScreenShot(stepId, "```[SCREENSHOT]``` Captured from previous step")
				}
			}
			it['errors'].each {
				this.logging.logError(stepId, "```[ERROR]``` " + it.toString())
			}
		}
		this.context.errors.clear()
	}
```

**Comment by Fhadel** [comment]
Hi, 

sorry late reply, im still stuck how to calll logScreenshot in method createErrorSteps dont know how to tweak the method, got error like this 

Caught: java.lang.NullPointerException: Cannot invoke method isEmpty() on null object
java.lang.NullPointerException: Cannot invoke method isEmpty() on null object
	at com.extension.reportportal.listener.ReportPortalListener$_createErrorSteps_closure3.doCall(ReportPortalListener.groovy:174)

am i missing something?

**Comment by NHP95** [comment]
The `it['screenshot']` in your case should be the screenshot **array**. I did some refactors in `ReportPortalContext` class to make it look like the sample provided.

**Comment by Fhadel** [comment]
may i see your refactored code of `ReportPortalContext` ?

**Comment by NHP95** [comment]
> may i see your refactored code of `ReportPortalContext` ?

Here ya go

```java
        public collectIssues() {
		def hasNewError = !this.getNewErrors().isEmpty()
		def isScreenShotOnFailureEnabled = GlobalVariable.RP_SCREENSHOT_ON_FAILURE
		if (hasNewError && isScreenShotOnFailureEnabled) {
			ReportPortalContext.captureScreenShotForReportportal()
		}
		this.errors.add([('errors') : this.getNewErrors(), ('time') : DateUtils.getISOCurrentDate('UTC'),
			('screenshot') : this.screenshots])
	}
	@Keyword
	public static void captureScreenShotForReportportal() {
		try {
			def scrFile = ((TakesScreenshot)DriverFactory.getWebDriver()).getScreenshotAs(OutputType.BYTES);
			screenshots.add(scrFile)
		}
		catch (BrowserNotOpenedException e) {
			KeywordLogger log = new KeywordLogger()
			log.logWarning("Browser is not opened.")
		}
	}
	private getNewErrors() {
		return ErrorCollector.getCollector().getErrors() - this.foundErrors
	}
```

**Comment by Fhadel** [comment]
i understand now, how the code works it take almost a month to understand the code, and also with your help too like hint how to do this i can make it happen

Thanks for your assistance and help

**Comment by NHP95** [comment]
Nice. I’m glad you made it.

**Comment by Fhadel** [comment]
do you know whats caused this error code 

 Can't log screenshot : 
Response{protocol=http/1.1, code=407, message=authenticationrequired, url=http://10.5.42.183:8080/api/v1/piloting_katalon/log}

do i miss something in authentication key or something?

**Comment by NHP95** [comment]
I believe the authentication is missing.
