### ISSUE TITLE
OutBound issue

### ISSUE THREAD

**Issue by arun-alladi** [NHP95/ReportPortal-Katalon-Integration#6]
Hello NHP95, 

Greetings!!

Really Thankfull to you for all the listeners developed for Integrating Katalon with ReportPortal.

Recently i used this code and it all went well untill i executed 4 testcases, but when 5th test cases is added it throws array outbound issue, please see below snapshot for the error.

Appreciate if you could please help me in solving this. Thank you in Advance !! 

![image](https://user-images.githubusercontent.com/57362810/69779364-c90ade80-1175-11ea-94da-aae05442a9ab.png)

**Comment by NHP95** [comment]
May I see how your suite looks like? And 5th test case as well? Have you used any test listeners?

**Comment by arun-alladi** [comment]
Hi , 

Thank you for the quick response, Please see the attachment for Test Suite
![image](https://user-images.githubusercontent.com/57362810/69800279-ec984e00-11a2-11ea-9290-56aacf0437fd.png)


FIfth Test Case : Its just a single-statement to open browser 

![image](https://user-images.githubusercontent.com/57362810/69800356-16ea0b80-11a3-11ea-9b7a-8f4ad9e85082.png)

its not the problem with 5th Test case, even if change the order then the latest 5th TC also fails with the same error.

**Comment by NHP95** [comment]
Thanks. Is there any listener used along with the reportportal one?

**Comment by arun-alladi** [comment]
Yes ,I have created a new listener  in 'Test Listener' folder which triggers before TestSuite and After TestSuite.

**Comment by NHP95** [comment]
Thanks for the clarification. I think I know how to reproduce it.

**Comment by arun-alladi** [comment]
Appreciate , if you cound kindly help me in solving this.

**Comment by NHP95** [comment]
Are you using the 7.x version of Katalon?

**Comment by arun-alladi** [comment]
Hi ,

Yes, am using the Katalon 7.

**Comment by NHP95** [comment]
Thanks for the info, I know what's going on. I tried on both version 6.x and 7.x and it only worked on older versions. In the latest version, it ran into an encoding error in Katalon 7.x. I'll get back to you asap.

**Comment by arun-alladi** [comment]
Thanks a lot, for your time and efforts @NHP95

**Comment by NHP95** [comment]
The updated code is available on the [developer branch](https://github.com/NHP95/ReportPortal-Katalon-Integration/tree/develop) Please help check it against your test suite to see if the issue still remains.

**Comment by arun-alladi** [comment]
Latest is absolutely working good in all the scenarios. I have tested as per my knowledge. Once again Thanks a lot for your time and Efforts. will get back to you if i find any more issues.

**Comment by NHP95** [comment]
Thanks. 💃
